<a href="https://colab.research.google.com/github/Kristina140699/Master-Data-Science-in-Python/blob/main/Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Arrays
## Single Dimensional Array

In [2]:
import numpy as np
n1 = np.array([10, 20, 30, 40, 50])
n1

array([10, 20, 30, 40, 50])

In [2]:
type(n1)

numpy.ndarray

## Multi Dimensional Array

In [7]:
n2 = np.array([[1,2,3,4,5],[11, 12, 13, 14, 15],[10, 20, 30, 40, 50]])
n2

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [10, 20, 30, 40, 50]])

In [8]:
type(n2)

numpy.ndarray

## Zero Arrays

In [5]:
n0 = np.zeros((5,2))
n0

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Numpy array with same number

In [7]:
n4 = np.full((2,3), 14)
n4

array([[14, 14, 14],
       [14, 14, 14]])

## Numpy array within a range

In [9]:
n5 = np.arange(10, 20) #this prints all the numbers including 10 and excluding 20
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
n5 = np.arange(15, 65, 5) # here 5 is the step/ interval after which the numbers will be printed.
n5

array([15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

## Numpy array with random numbers

In [13]:
n6 = np.random.randint(50, 250, 5)
n6

array([125, 209, 106, 188, 236])

## Shape of Numpy array

In [18]:
n7 = np.array([[1,2,3], [4,5,6]])
n7

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
n7.shape

(2, 3)

In [20]:
n7.shape = (3, 2)
n7

array([[1, 2],
       [3, 4],
       [5, 6]])